### ISSUE TITLE
readTLE speed improvement

### ISSUE THREAD

**Issue by helgasoft** [Rafael-Ayala/asteRisk#5]
Function **readTLE** uses _readLines_ to read from an URL.  When the URL file is big, this is a slow operation.
Decided to compare "_download first + readTLE_" versus "_readTLE only_". Results show almost **double speed** when file is downloaded first.
```r
url <- 'https://www.celestrak.com/NORAD/elements/active.txt'
dnld <- function(url) {
 destfile <- tempfile('aster')
 download.file(url, destfile) #, method='curl')
 out <- readTLE(destfile)
 out
}
library(microbenchmark)
p <- microbenchmark(readTLE(url), dnld(url), times=1)
print(p)

Unit: seconds
        expr       min        lq      mean    median        uq       max neval
readTLE(url) 12.498741 12.498741 12.498741 12.498741 12.498741 12.498741     1
   dnld(url)  6.676866  6.676866  6.676866  6.676866  6.676866  6.676866     1
```

**Comment by Rafael-Ayala** [comment]
This is great! I have modified readTLE to detect if an URL is being provided, in which case download to a temporal file will first be performed. I've pushed changes to the development version on GitHub! Let me know if that reaches the same performance you observed!

**Comment by helgasoft** [comment]
I ran the same test **before** upgrading _asteRisk_ and got a different (but consistent) result this time:
```
> print(p)
Unit: seconds
         expr      min       lq     mean   median       uq      max neval
 readTLE(url) 18.46286 18.46286 18.46286 18.46286 18.46286 18.46286     1
    dnld(url) 12.37508 12.37508 12.37508 12.37508 12.37508 12.37508     1
```
Improvement in speed was 2/3 instead of 1/2. No idea what the reason is. The online file size has increased by only 6KB for a total of 842KB.  
Anyway, the latest _asteRisk_ 1.4.9999 confirms the speed improvement.
